version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - /path/on/host:/var/lib/zookeeper

    broker:
        image: confluentinc/cp-kafka:7.0.1
        container_name: broker
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: "Abhinav1712"

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "resource-user"
            POSTGRES_PASSWORD: "Abhinav@1712"
            POSTGRES_DB: "resource-user"

    mysql-user:
        image: mysql:latest
        container_name: mysql-user
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Abhinav@1712"
            MYSQL_DATABASE: "resource-user"
            MYSQL_USER: "resource-user"
            MYSQL_PASSWORD: "Abhinav@1712"
    mysql-allocator: # Add a new MySQL instance
        image: mysql:latest
        container_name: mysql-allocator
        ports:
            - "3307:3306" # Use a different host port to avoid conflicts
        environment:
            MYSQL_ROOT_PASSWORD: "Abhinav@1712" # Change the password if needed
            MYSQL_DATABASE: "resource-allocator" # Change the database name if needed
            MYSQL_USER: "resource-allocator" # Change the username if needed
            MYSQL_PASSWORD: "Abhinav@1712"
# Add any additional services or configurations as needed
