# Generated by Django 5.0 on 2023-12-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=100)),
                (
                    "container_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("starting_date", models.DateField()),
                ("end_date", models.DateField(default=None, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("killed", "Killed"),
                            ("stopped", "Stopped"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("machine_name", models.CharField(max_length=100)),
                (
                    "container_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("port_used", models.IntegerField(default=None)),
                ("uid", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "machineallocation",
            },
        ),
    ]
