# Generated by Django 4.2.4 on 2023-08-20 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=100)),
                ("container_id", models.CharField(max_length=100)),
                ("starting_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("machine_name", models.CharField(max_length=100)),
                ("container_name", models.CharField(max_length=100)),
                ("instance_id", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
