# Generated by Django 4.2.4 on 2023-08-20 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("allocate_machine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineallocation",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machineallocation",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
