# Generated by Django 4.0 on 2023-08-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_machine', '0002_machineallocation_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machineallocation',
            table='machine-allocation',
        ),
    ]
