# Generated by Django 4.0 on 2023-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_machine', '0003_alter_machineallocation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocation',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
