# Generated by Django 4.0 on 2023-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_machine', '0004_alter_machineallocation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineallocation',
            name='port_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
