# Generated by Django 4.0 on 2023-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_machine', '0006_alter_machineallocation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineallocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('killed', 'Killed'), ('stopped', 'Stopped')], default=None, max_length=20, null=True),
        ),
    ]
