# Generated by Django 4.0 on 2023-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_machine', '0007_machineallocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineallocation',
            name='uid',
            field=models.UUIDField(default='291b4b9d-6baa-4838-a0d4-d2e4eeb650ea'),
            preserve_default=False,
        ),
    ]
