# Generated by Django 4.0 on 2023-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=355)),
                ('phone_number', models.CharField(max_length=355)),
                ('gender', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=True)),
                ('sms_notification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
    ]
