# Generated by Django 5.0 on 2023-12-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
