# Generated by Django 4.0 on 2023-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usermodel',
            name='users_userm_email_40b93c_idx',
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
