# Generated by Django 5.0 on 2023-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_usermodel_email_alter_usermodel_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
