# Generated by Django 4.2.8 on 2023-12-31 15:57

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[],
            options={
                "managed": False,
            },
        ),
    ]
